import { NextRequest, NextResponse } from "next/server";
import { db } from "@/src/db";
import { projects, versions, episodes } from "@/src/db/schema";
import { eq } from "drizzle-orm";
import { z } from "zod/v4";

const generateCoreSchema = z.object({
  title: z.string().min(1, "Title is required.").max(500),
  input_type: z.enum(["idea", "draft"]),
  raw_story: z.string().min(1, "Story text is required."),
});

// Placeholder episode data — will be replaced by AI agents in Phase 8
const PLACEHOLDER_EPISODES = [
  {
    episodeNumber: 1,
    title: "Episode 1: The Hook",
    scriptContent:
      "[Placeholder] This is where the opening hook script will be generated by the AI Story Architect agent.",
  },
  {
    episodeNumber: 2,
    title: "Episode 2: The Escalation",
    scriptContent:
      "[Placeholder] This is where the rising tension script will be generated by the AI Story Architect agent.",
  },
  {
    episodeNumber: 3,
    title: "Episode 3: The Cliffhanger",
    scriptContent:
      "[Placeholder] This is where the cliffhanger script will be generated by the AI Story Architect agent.",
  },
];

// POST /api/generate-core — Initialize project and generate raw episodic scripts
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const parsed = generateCoreSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: { code: "INVALID_BODY", message: parsed.error.issues[0].message } },
        { status: 400 }
      );
    }

    const { title, input_type, raw_story } = parsed.data;

    // --- Transactional creation: Project → Version → Episodes → link activeVersionId ---
    const result = await db.transaction(async (tx) => {
      // 1. Create the Project
      const [project] = await tx
        .insert(projects)
        .values({
          title,
          inputType: input_type,
          originalRawStory: raw_story,
        })
        .returning();

      // 2. Create the initial Version (status: pending)
      const [version] = await tx
        .insert(versions)
        .values({
          projectId: project.id,
          parentVersionId: null,
          commitMessage: "Initial Generation",
          analysisStatus: "pending",
        })
        .returning();

      // 3. Create placeholder Episodes
      const episodeRows = await tx
        .insert(episodes)
        .values(
          PLACEHOLDER_EPISODES.map((ep) => ({
            projectId: project.id,
            versionId: version.id,
            episodeNumber: ep.episodeNumber,
            title: ep.title,
            scriptContent: ep.scriptContent,
          }))
        )
        .returning();

      // 4. Link the active version back to the project
      await tx
        .update(projects)
        .set({ activeVersionId: version.id })
        .where(eq(projects.id, project.id));

      return { project, version, episodes: episodeRows };
    });

    return NextResponse.json(
      {
        project_id: result.project.id,
        version_id: result.version.id,
        analysis_status: result.version.analysisStatus,
        episodes: result.episodes.map((ep) => ({
          id: ep.id,
          episode_number: ep.episodeNumber,
          title: ep.title,
        })),
        message: "Core generation complete. Trigger /api/analyze-version next.",
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("POST /api/generate-core error:", error);
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message: "Failed to generate core project." } },
      { status: 500 }
    );
  }
}
